### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by dig412** [SoYoureAWaffleMan/sov-hub#1]
* `filter` param for the hub call should be `filters`
* stream start time is available in `ticketSummary->startDateTime`, including timezone
* target url is either our event page or `ticketSummary->url`

**Comment by SoYoureAWaffleMan** [comment]
👍 aknowledged. What's the whats the value of the `filters` param? `{sov:true}`?

**Comment by dig412** [comment]
Yep, contents of the param is fine, I've pushed a change to production to recognise that option
